### ISSUE TITLE
"Todo" componenten duidelijke informatie geven op website

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/documentatie#1079]
Niet alle componenten hebben nu een description in het component overzicht, dat is niet handig. De mooie description is pas klaar aan het eind van het help wanted proceces, maar we kunnen nu al een voorzet doen op de website.

Componenten:

- [ ] Alert
- [ ] Alert dialog
- [ ] Avatar
- [ ] Calendar
- [ ] Card as link
- [ ] Checkbox
- [ ] Data badge
- [ ] Date input group
- [ ] Date picker
- [ ] Definition list
- [ ] Dot badge
- [ ] Drawer
- [ ] Fieldset
- [ ] File input
- [ ] Form field
- [ ] Form field checkbox option
- [ ] Form field option label
- [ ] Form field partial
- [ ] Form field partial label
- [ ] Form field radio option
- [ ] Heading 2
- [ ] Heading 3
- [ ] Heading 4
- [ ] Heading 5
- [ ] Heading 6
- [ ] Heading group
- [ ] Icon
- [ ] Invalid form alert
- [ ] Language navigation
- [ ] Legend
- [ ] Link list
- [ ] Non modal dialog
- [ ] Notification banner
- [ ] Number input
- [ ] Page footer
- [ ] Page header
- [ ] Pagination
- [ ] Password input
- [ ] Pre heading
- [ ] Progress bar
- [ ] Radio button
- [ ] Rich text content
- [ ] Status badge
- [ ] Strong
- [ ] Sub heading
- [ ] Summary list
- [ ] Switch
- [ ] Task list
- [ ] Text input group
- [ ] Textarea
- [ ] Toggletip
- [ ] Video

## Acceptatie-criteria

- Description is ingevuld in de component mdx, in de front-matter en in de `description` export
- Er is een discussion aangemaakt in de backlog repository
- Er is een link ingevuld naar de GitHub Discussion in het Help wanted
-
