### ISSUE TITLE
Toevoegen referenties naar gerelateerde WCAG-pagina's bij de componenten die in 2024 naar Candidate-status gaan

### ISSUE THREAD

**Issue by rianrietveld** [nl-design-system/documentatie#1375]
Bij de documentatie van een component staan onder andere de Acceptatiecriteria.
Hierbij staan de WCAG 2.2 succescriteria die op een component van toepassing zijn.
Bij alle componenten met de status community moeten de regelateerde WCAG-succescriteria worden toegevoegd onder het kopje Acceptatiecriteria.

Bijvoorbeeld voor een "Button", zie https://documentatie-git-docs-component-wcag-criteria-nl-design-system.vercel.app/button/#acceptatiecriteria
ZIe PR: https://github.com/nl-design-system/documentatie/pull/1209

Gerelateerd:
https://github.com/nl-design-system/documentatie/blob/main/docs/componenten/paragraph/_guidelines.md

De referentie bestaat uit de titel (h3-kopje) dat tevens een link is naar de WCAG-pagina op nldesignsystem.nl/wcag plus een korte samenvatting.

De tekst van de samenvatting kan worden gehaald uit de summaries (.md bestanden) van de WCAG-pagina's, zie 
https://github.com/nl-design-system/documentatie/tree/main/docs/wcag/summaries

In de storybooks van Utrecht en Amsterdam is ook al een en ander te vinden:
- https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-button--docs#relevante-wcag-succescriteria
- https://designsystem.amsterdam/?path=/docs/components-buttons-button--docs#relevant-wcag-requirements

## Plek om de documentatie neer te zetten:

Bij de componenten, bijvoorbeeld voor Accordion:
https://nldesignsystem.nl/accordion/

Deze staan in de webste-code onder docs/componenten:
https://github.com/nl-design-system/documentatie/tree/main/docs/componenten

## Componenten nu de community-status hebben:

- **Project**: https://github.com/orgs/nl-design-system/projects/29/views/1?filterQuery=status%3ACommunity
- **Issues**: https://github.com/nl-design-system/backlog/issues?q=is%3Aissue+is%3Aopen+label%3ACommunity. Hier staan ook de links naar de discussies over de betreffende component.

Als je start met een component, maak een bijbehorende PR en refereer in de omschrijving naar dit issue.

Tracking: Vink af wat klaar is, met het bijbehorende issue erbij vermeldt. 

 - [ ] [Accordion](https://www.nldesignsystem.nl/accordion)
 - [ ] [Blockquote](https://www.nldesignsystem.nl/blockquote)
 - [ ] [Breadcrumb navigation](https://www.nldesignsystem.nl/breadcrumb-navigation)
 - [x] [Button ](https://www.nldesignsystem.nl/button)#1392 
 - [ ] [Form field error message](https://www.nldesignsystem.nl/form-field-error-message)
 - [ ] [Heading 1](https://www.nldesignsystem.nl/heading-1)
 - [ ] [Heading 2](https://www.nldesignsystem.nl/heading-2)
 - [ ] [Heading 3](https://www.nldesignsystem.nl/heading-3)
 - [ ] [Heading 4](https://www.nldesignsystem.nl/heading-4)
 - [ ] [Heading 5](https://www.nldesignsystem.nl/heading-5)
 - [ ] [Heading 6](https://www.nldesignsystem.nl/heading-6)
 - [x] [Login Link](https://www.nldesignsystem.nl/login-link) #1595
 - [ ] [Ordered List](https://www.nldesignsystem.nl/ordered-list)
 - [ ] [Unordered List](https://www.nldesignsystem.nl/unordered-list) #1473

## Potentiële Candidate Componenten

1.  - [x] [Code](https://www.nldesignsystem.nl/code) #1591
2.  - [x] [Code Block](https://www.nldesignsystem.nl/code-block) #1592
3.  - [x] [Color Sample](https://www.nldesignsystem.nl/color-sample) #1605
4.  - [x] [Data Badge](https://www.nldesignsystem.nl/data-badge) #1610
5.  - [x] [Heading](https://www.nldesignsystem.nl/heading) #1598
6.  - [x] [Link](https://www.nldesignsystem.nl/link)  #1499 
7.  - [x] [Mark](https://www.nldesignsystem.nl/mark) #1587
8.  - [x] [Number badge](https://www.nldesignsystem.nl/number-badge) #1611
9.  - [x] [Paragraph](https://www.nldesignsystem.nl/paragraph) #1588
10.  - [x] [Skip Link](https://www.nldesignsystem.nl/skip-link) #1612

**Comment by rianrietveld** [comment]
@MarjonBakker en  @Robbert  

Even een brain fart: voor de acceptatiecriteria testen we nu alleen tegen WCAG. Maar ook de code moet kloppen, zeker net zo belangrijk. 

Ik ben nu bezig met de Unordered List. Waar ik het vaak fout zie gaan is dat, voor de layout, er allemaal divs/spans of zelfs kopjes tussen de li's worden gezet, en dat mag niet van de HTML-specs.

Zou onderstaande als eerste item bij de acceptatiecriteria passen?

Zorg dat de geïmplementeerde component in de frontend valideert voor correcte HTML en CSS
Test bijvoorbeeld bij het W3C via de [Markup Validation Service](https://validator.w3.org/) en de [CSS Validation Service](https://jigsaw.w3.org/css-validator/). Of zorg ervoor dat je deze teksten geautomatisserd kunt uitvoeren.

**Comment by MarjonBakker** [comment]
@rianrietveld @Robbert

> Zou onderstaande als eerste item bij de acceptatiecriteria passen?
> 
> > Zorg dat de geïmplementeerde component in de frontend valideert voor correcte HTML en CSS.
> > Test bijvoorbeeld bij het W3C via de [Markup Validation Service](https://validator.w3.org/) en de [CSS Validation Service](https://jigsaw.w3.org/css-validator/). Of zorg ervoor dat je deze testen geautomatisserd kunt uitvoeren.

Ja, ik denk het wel. Dat ondervangt ook meteen WCAG-criterium 4.1.1. Dat kan dan apart blijven staan, maar volgens mij voldoe je altijd aan 4.1.1 als je valide HTML hebt gebruikt.

**Comment by MarjonBakker** [comment]
Gesloten, dit is wat we voor 2024 voor ogen hadden
