### ISSUE TITLE
Typ- en spellingsfouten verbeteren

### ISSUE THREAD

**Issue by MarjonBakker** [nl-design-system/documentatie#1385]
Op verzoek van @rianrietveld een issue voor kleine tekstverbeteringen.

- [x] `WCAG-succescriterium 3.1.2 Taal van onderdelen)` veranderen in `WCAG-succescriterium 3.1.2 Taal van onderdelen` op pagina https://www.nldesignsystem.nl/wcag/3.1.2/
- [x] Op https://www.nldesignsystem.nl/wcag/3.2.4 Linktekst in link `[3.2.4 Consistente Identification](https://www.w3.org/TR/WCAG22/#consistent-identification).` wijzigen in `[3.2.4 Consistent Identification](https://www.w3.org/TR/WCAG22/#consistent-identification).`
- [x] op https://nldesignsystem.nl/richtlijnen/stijl/iconen/: bij Gerelateerde WCAG Richtlijnen, de linktekst van [1.4.11 Non text contrast](https://nldesignsystem.nl/wcag/1.4.11) aanpassen naar Contrast van niet-tekstuele content.
- [x] op de richtlijnen over [Stijl](https://nldesignsystem.nl/richtlijnen/stijl/) verwijder punten achter de tekst van kopjes
- [x] In de `h1` op https://www.nldesignsystem.nl/richtlijnen/formulieren/buttons/duidelijk-buttontekst/: Voeg `e` in achter het woord 'Duidelijk'
- [x] Op https://www.nldesignsystem.nl/richtlijnen/formulieren/visueel-ontwerp/invoerveld-goed-aanklikbaar/ staat "Maak aanklikbare formuliervelden groot genoeg", maar de voorbeelden zijn buttons. Kunnen we niet beter 'formuliervelden' vervangen door 'interactieve elementen'?
- [x] Op componentenpagina's zoals https://documentatie-git-docs-component-wcag-criteria-nl-design-system.vercel.app/button in de accordion: `Versimpelt of gesplitst` vervangen door `Versimpeld of gesplitst`
- [x] Op https://www.nldesignsystem.nl/wcag/2.4.13 : "De Nederlandse vertaling van het WCAG-succescriterium 2.4.13 Focusweergave verschijnt binnenkort." Deze tekst is er inmiddels. dit zou moeten worden nagelopen voor alle uitlegpagina's met WCAG 2.2-criteria. onder het kopje 'W3C referenties'
- [x] Op https://www.nldesignsystem.nl/wcag/2.5.2 : 'het event' in plaats van 'de event'
- [x] Op https://nldesignsystem.nl/richtlijnen/formulieren/visueel-ontwerp/focus-goed-zichtbaar : 'Maak toetsenbord focus goed zichtbaar' vervangen door 'Maak toetsenbordfocus goed zichtbaar'
- [x] Op https://www.nldesignsystem.nl/wcag/3.2.1 klopt achter 'Engelstalige toelichting:' de linktekst niet: Dit moet zijn `On Focus` in plaats van `On Input`
