### ISSUE TITLE
Aan te maken en aan te vullen richtlijnen- en WCAG pagina's

### ISSUE THREAD

**Issue by MarjonBakker** [nl-design-system/documentatie#1451]
Sommige technische uitleg verdient een eigen pagina in de richtlijnen.

- [ ] Uitleg over up en down events ten behoeve van [2.5.2 Aanwijzerannulering](https://nldesignsystem.nl/wcag/2.5.2) en [button-component](https://documentatie-git-docs-component-wcag-criteria-nl-design-system.vercel.app/button)
- [ ] Bij Formulieren > Buttons > [Afbeeldingen als buttons](https://nldesignsystem.nl/richtlijnen/formulieren/buttons/afbeelding-als-button) voorbeelden meegeven hoe dit in code te doen. Ook DigiD logo als voorbeeld geven.
- [ ] Bij de Stijl > [Typografie](https://nldesignsystem.nl/richtlijnen/stijl/typografie) richtlijnen deze beter toespitsen op de WCAG richtlijnen, de hangen er nu helemaal onderaan bij zonder relatie tot de specifieke onderwerpen..
- [ ] Bij de Stijl > [Typografie](https://nldesignsystem.nl/richtlijnen/stijl/typografie) richtlijnen: het gebruik van rem/px beter beschrijven naar wat gewenst is.
- [ ] Bij de Stijl > [Typografie](https://nldesignsystem.nl/richtlijnen/stijl/typografie) richtlijnen: Uitleg over het vergroten van afstanden ten behoeve van 1.4.12 Tekstafstand
- [ ] Bij [2.4.6 Koppen en Labels](https://nldesignsystem.nl/wcag/2.4.6) mag nog wat meer informatie over labels. Er wordt nu alleen gesproken over labels bij formuliervelden (`label`-element), maar labels omvatten meer dan dat volgens de [definitie in WCAG](https://www.w3.org/WAI/WCAG22/Understanding/headings-and-labels.html#dfn-label).

gefixt in #1996
- [x] Op [Informeer gebruikers van screenreaders over het statusbericht](https://nldesignsystem.nl/richtlijnen/formulieren/status/screenreaders) staat een todo. bij de voorbeelden.
- [x] De do-don't sectie bij de richtlijnen een H2 kopje "Voorbeelden" geven.
- [x] Koppenstructuur acceptatiecriteria compponeten repareren.
